version: '3'
services:
  bcs:
    image: 10.0.1.8:5000/ethub-protocol-buff-v4:latest
    ports:
      - "8112:8112"
      - "10001:10002"
    volumes:
      - /home/Voultech/app/ethub-protocol-buff-bcs/libs:/app/ethub/libs
      - /home/Voultech/app/ethub-protocol-buff-bcs/config:/app/ethub/config
      - /home/Voultech/app/ethub-protocol-buff-bcs/logs:/app/ethub/logs
      - /home/Voultech/app/ethub-protocol-buff-bcs/ethub-protocol-buff-1.3.jar:/app/ethub/ethub.jar
  ib:
    image: 10.0.1.8:5000/ethub-protocol-buff-v4:latest
    ports:
      - "8114:8112"
      - "10010:10002"
    volumes:
      - /home/Voultech/app/ethub-protocol-buff-ib/libs:/app/ethub/libs
      - /home/Voultech/app/ethub-protocol-buff-ib/config:/app/ethub/config
      - /home/Voultech/app/ethub-protocol-buff-ib/logs:/app/ethub/logs
      - /home/Voultech/app/ethub-protocol-buff-ib/ethub-protocol-buff-1.3.jar:/app/ethub/ethub.jar

  bbg:
    image: 10.0.1.8:5000/ethub-protocol-buff-v4:latest
    ports:
      - "8115:8112"
      - "10016:10002"
    volumes:
      - /home/Voultech/app/ethub-protocol-buff-bbg/libs:/app/ethub/libs
      - /home/Voultech/app/ethub-protocol-buff-bbg/config:/app/ethub/config
      - /home/Voultech/app/ethub-protocol-buff-bbg/logs:/app/ethub/logs
      - /home/Voultech/app/ethub-protocol-buff-bbg/ethub-protocol-buff-1.3.jar:/app/ethub/ethub.jar

